'use client';
import { useEffect, useState } from 'react';
import { useSiteConfig } from './use-site-config';
const numberLabel = index => String(index + 1).padStart(2, '0');
function Arrow({ diagonal = true }) {
 return <svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d={diagonal ? 'M5 19 19 5M5 5h14v14' : 'M4 12h16m-6-6 6 6-6 6'} stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round"/></svg>;
}
function Brand({ brand }) { return <a className="brand" href="#conteudo"><span className="brand-symbol">{brand.symbol}</span><span>{brand.name}<small>{brand.subtitle}</small></span></a>; }
export default function Home() {
 const config = useSiteConfig();
 const { brand, header, hero, ticker, solutions, about, process, faq, contact, footer, appearance, profile } = config;
 const [menu,setMenu] = useState(false), [activeService,setActiveService] = useState(0), [openFaq,setOpenFaq] = useState(null), [interest,setInterest] = useState(''), [message,setMessage] = useState(''), [copied,setCopied] = useState(false), [copyError,setCopyError] = useState(false);
 const serviceIndex = Math.min(activeService, Math.max(0,solutions.items.length-1));
 const currentService = solutions.items[serviceIndex];
 const selectedInterest = [...solutions.items.map(item=>item.title),contact.otherOption].includes(interest) ? interest : solutions.items[0]?.title || contact.otherOption;
 const phone = contact.whatsapp || processEnvNumber();
 useEffect(() => {
  if(!appearance.animations || window.matchMedia('(prefers-reduced-motion: reduce)').matches) return;
  const elements = document.querySelectorAll('.site-root [data-reveal]');
  const observer = new IntersectionObserver(entries => entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('shown');observer.unobserve(entry.target);}}),{threshold:.08});
  elements.forEach(element=>{element.classList.add('will-reveal');observer.observe(element);});
  return ()=>{observer.disconnect();elements.forEach(element=>element.classList.remove('will-reveal','shown'));};
 },[appearance.animations,hero.visible,solutions.visible,about.visible,process.visible,faq.visible,contact.visible]);
 function startConversation(item){setInterest(item?.title || contact.otherOption);}
 function submit(event){event.preventDefault();const name=new FormData(event.currentTarget).get('name').trim();if(name){setMessage(contact.messageTemplate.replaceAll('{nome}',name).replaceAll('{assunto}',selectedInterest));setCopied(false);setCopyError(false);}}
 return <div className={'site-root '+(!appearance.animations?'motion-off':'')} style={{'--accent':appearance.orange,'--base':appearance.background,'--text':appearance.text}}>
 {profile.demo&&<div className="demo-content-notice" role="note">{profile.demoNotice}</div>}
 <a className="skip" href="#conteudo">{config.accessibility.skipLabel}</a>
 <header className="site-header"><div className="container header-inner"><Brand brand={brand}/><button className="menu-button" type="button" aria-expanded={menu} aria-controls="site-navigation" onClick={()=>setMenu(!menu)}>{header.menuLabel}</button><nav id="site-navigation" className={menu?'is-open':''} aria-label="Principal">{header.navigation.map((link,i)=><a key={i} href={link.href} onClick={()=>setMenu(false)}>{link.label}</a>)}</nav><a className="header-contact" href={header.contactHref}>{header.contactLabel}</a></div></header>
 <main id="conteudo">
 {hero.visible&&<section className="opening"><div className="container opening-grid"><div className="opening-copy"><p className="kicker"><span/>{hero.eyebrow}</p><h1>{hero.title}<br/>{hero.secondLine} <span>{hero.highlight}</span></h1><p className="opening-description multiline">{hero.description}</p><div className="opening-actions"><a className="cta cta-dark" href={hero.primaryHref}>{hero.primaryLabel}<Arrow/></a><a className="quiet-link" href={hero.secondaryHref}>{hero.secondaryLabel}</a></div></div><aside className="professional-portrait" aria-label={profile.fullName}><div className="portrait-image">{about.photo?<img src={about.photo} alt={about.photoAlt} fetchPriority="high"/>:<div className="portrait-placeholder"><svg viewBox="0 0 200 230" aria-hidden="true"><circle cx="100" cy="72" r="38"/><path d="M24 224v-29c0-43 34-72 76-72s76 29 76 72v29"/></svg><span>{profile.photoPlaceholder}</span></div>}</div><div className="portrait-caption"><span className="portrait-caption-mark">{brand.symbol}</span><div><h2>{profile.fullName}</h2><p>{profile.role}</p>{profile.company&&<small>{profile.company}</small>}</div></div>{profile.startYear&&<div className="experience-tag"><strong>{profile.startYear}</strong><span>{profile.experienceLabel}</span></div>}</aside><div className="opening-bottom"><span>{hero.footnote}</span><a href={hero.scrollHref}>{hero.scrollLabel}<Arrow diagonal={false}/></a></div></div></section>}
 {(profile.startYear||profile.company||profile.location)&&<section className="professional-facts container" aria-label="Informações profissionais">{[[profile.experienceLabel,profile.startYear],[profile.companyLabel,profile.company],[profile.locationLabel,profile.location]].filter(([,value])=>value).map(([label,value])=><div key={label}><span>{label}</span><strong>{value}</strong></div>)}</section>}
 {ticker.visible&&<div className="expertise-bar"><div className="container">{ticker.items.map((item,i)=><span key={i}><span aria-hidden="true">{ticker.symbol}</span>{item}</span>)}</div></div>}
 {solutions.visible&&<section id="solucoes" className="section container"><div className="section-intro" data-reveal><div><p className="kicker">{solutions.eyebrow}</p><h2 className="multiline">{solutions.title}</h2></div><p className="multiline">{solutions.description}</p></div><div className="solution-explorer" data-reveal><div className="solution-tabs" role="tablist" aria-orientation="vertical" aria-label={solutions.title.replaceAll('\n',' ')}>{solutions.items.map((item,i)=><button type="button" role="tab" tabIndex={serviceIndex===i?0:-1} aria-selected={serviceIndex===i} aria-controls="solution-panel" id={'solution-tab-'+i} key={i} onClick={()=>setActiveService(i)} onKeyDown={event=>{if(['ArrowDown','ArrowUp','Home','End'].includes(event.key)){event.preventDefault();const next=event.key==='Home'?0:event.key==='End'?solutions.items.length-1:(serviceIndex+(event.key==='ArrowDown'?1:-1)+solutions.items.length)%solutions.items.length;setActiveService(next);document.getElementById('solution-tab-'+next)?.focus();}}}><span>{numberLabel(i)}</span><strong>{item.title}</strong><Arrow/></button>)}</div>{currentService&&<div id="solution-panel" role="tabpanel" aria-labelledby={'solution-tab-'+serviceIndex} className={'solution-detail '+(currentService.featured?'is-featured':'')}><div className="solution-decoration" aria-hidden="true">{currentService.icon}</div><div className="solution-content" key={serviceIndex}><span className="detail-number">{numberLabel(serviceIndex)}</span><h3>{currentService.title}</h3><p className="multiline">{currentService.description}</p><a className="cta cta-dark" href={currentService.href} onClick={()=>startConversation(currentService)}>{currentService.buttonLabel}<Arrow/></a></div></div>}</div><p className="section-note">{solutions.footnote}</p></section>}
 {about.visible&&<section id="sobre" className="about-section"><div className="container about-layout"><div className="about-intro" data-reveal><p className="kicker">{about.eyebrow}</p><h2 className="multiline">{about.title}</h2><div className="professional-name"><strong>{profile.fullName}</strong><span>{profile.role}</span></div><div className="about-body">{about.paragraphs.map((paragraph,i)=><p className="multiline" key={i}>{paragraph}</p>)}</div><a className="quiet-link" href={about.href}>{about.buttonLabel}<Arrow/></a></div><div className="person-card" data-reveal>{about.photo?<img className="person-photo" src={about.photo} alt={about.photoAlt} loading="lazy"/>:<div className="person-statement"><span className="statement-label">{about.portraitLabel}</span><span className="statement-quote" aria-hidden="true">“</span><p className="multiline">{about.portraitText}</p><div className="statement-sign"><span>{brand.symbol}</span><strong>{about.signature}</strong></div></div>}<div className="personal-values">{about.values.map((value,i)=><div key={i}><span>{numberLabel(i)}</span><div><h3>{value.title}</h3><p>{value.description}</p></div></div>)}</div></div></div></section>}
 {(profile.milestones.some(item=>item.title.trim())||profile.credentials.some(item=>item.title.trim()))&&<section id="trajetoria" className="career-section section container"><div className="career-columns">{profile.milestones.some(item=>item.title.trim())&&<div><h2>{profile.trajectoryTitle}</h2><div className="career-timeline">{profile.milestones.filter(item=>item.title.trim()).map((item,i)=><article key={i} data-reveal><span>{item.period}</span><div><h3>{item.title}</h3><p>{item.description}</p></div></article>)}</div></div>}{profile.credentials.some(item=>item.title.trim())&&<div className="credentials"><h2>{profile.credentialsTitle}</h2>{profile.credentials.filter(item=>item.title.trim()).map((item,i)=><a key={i} href={item.href}><span aria-hidden="true">↗</span><div><h3>{item.title}</h3><p>{item.description}</p></div></a>)}</div>}</div></section>}
 {process.visible&&<section id="processo" className="section container"><div className="section-intro" data-reveal><div><p className="kicker">{process.eyebrow}</p><h2 className="multiline">{process.title}</h2></div><p>{process.description}</p></div><div className="process-line">{process.items.map((item,i)=><article key={i} data-reveal><div className="process-number"><span>{numberLabel(i)}</span><div/></div><h3>{item.title}</h3><p className="multiline">{item.description}</p></article>)}</div></section>}
 {faq.visible&&<section id="faq" className="questions-section"><div className="container questions-layout"><div className="questions-intro" data-reveal><p className="kicker">{faq.eyebrow}</p><h2 className="multiline">{faq.title}</h2><p>{faq.description}</p></div><div className="question-list" data-reveal>{faq.items.map((item,i)=><div className={'question '+(openFaq===i?'is-open':'')} key={i}><h3><button id={'faq-question-'+i} type="button" aria-expanded={openFaq===i} aria-controls={'faq-answer-'+i} onClick={()=>setOpenFaq(openFaq===i?null:i)}><span className="question-number">{numberLabel(i)}</span><span>{item.question}</span><span className="question-toggle" aria-hidden="true">+</span></button></h3><div id={'faq-answer-'+i} role="region" aria-labelledby={'faq-question-'+i} className="question-answer" inert={openFaq!==i}><div><p className="multiline">{item.answer}</p></div></div></div>)}</div></div></section>}
 {contact.visible&&<section id="contato" className="contact-section"><div className="container contact-layout"><div data-reveal><p className="kicker">{contact.eyebrow}</p><h2 className="multiline">{contact.title}</h2><p className="contact-description multiline">{contact.description}</p>{(profile.company||profile.location)&&<div className="contact-professional"><strong>{profile.company}</strong><span>{profile.location}</span></div>}<div className="professional-socials">{profile.socialLinks.filter(item=>item.label.trim()).map((item,i)=><a href={item.href} key={i}>{item.label}<Arrow/></a>)}</div><div className="contact-signature"><span>{brand.symbol}</span><strong>{contact.signature}</strong></div></div><form className="contact-form" onSubmit={submit} data-reveal><label htmlFor="name">{contact.nameLabel}</label><input id="name" name="name" required maxLength={60} autoComplete="given-name" placeholder={contact.namePlaceholder}/><label htmlFor="interest">{contact.interestLabel}</label><select id="interest" value={selectedInterest} onChange={event=>setInterest(event.target.value)}>{solutions.items.map((item,i)=><option key={i}>{item.title}</option>)}<option>{contact.otherOption}</option></select><button className="cta cta-accent" type="submit">{contact.buttonLabel}<Arrow/></button><p className="form-note">{contact.footnote}</p>{message&&<div className="message-result" aria-live="polite"><p>{message}</p>{(/^[0-9]{12,13}$/.test(phone)&&phone!=='5500000000000')?<a className="cta cta-accent" href={'https://wa.me/'+phone+'?text='+encodeURIComponent(message)} target="_blank" rel="noopener noreferrer">{contact.whatsappLabel}<Arrow/></a>:<><button className="copy-button" type="button" onClick={async()=>{try{await navigator.clipboard.writeText(message);setCopied(true);setCopyError(false);}catch{setCopyError(true);}}}>{copied?contact.copiedLabel:contact.copyLabel}</button>{copyError&&<p>{contact.copyError}</p>}<p>{contact.missingContact}</p></>}</div>}</form></div></section>}
 </main><footer className="site-footer" id="rodape"><div className="container"><div className="footer-top"><p>{footer.description}</p><a href="#conteudo">{footer.backToTop}<Arrow/></a></div><div className="footer-wordmark">{brand.name}<span>.</span></div><div className="footer-links">{footer.links.map((link,i)=><a href={link.href} key={i}>{link.label}<Arrow/></a>)}</div><div className="footer-bottom"><span>{footer.copyright}</span><p>{footer.legalText}</p></div></div></footer>
 </div>;
}
function processEnvNumber(){return process.env.NEXT_PUBLIC_WHATSAPP_NUMBER || '';}
