export const STORAGE_KEY = 'flaviano-site-config-v1';
export const defaults = {
  brand: { name: 'flaviano', symbol: 'f.', subtitle: 'CONSULTOR DE CRÉDITO' },
  seo: { title: 'Flaviano · Crédito com clareza', description: 'Conheça o trabalho de Flaviano em crédito consignado. Orientação para entender opções, comparar condições e decidir com clareza.' },
  appearance: { orange: '#f47b42', background: '#ffffff', text: '#232423', animations: true },
  header: { menuLabel: 'Menu ☰', contactLabel: 'Vamos conversar ↗', contactHref: '#contato', navigation: [{ label: 'Sobre mim', href: '#sobre' }, { label: 'Soluções', href: '#solucoes' }, { label: 'Como funciona', href: '#processo' }] },
  hero: { visible: true, eyebrow: 'FLAVIANO / CONSULTOR DE CRÉDITO', title: 'Crédito pensado', secondLine: 'para', highlight: 'você.', description: 'Suas opções de crédito, explicadas sem complicação.\nConsignado, portabilidade e refinanciamento com atendimento pessoal.', primaryLabel: 'Fale comigo', primaryHref: '#contato', secondaryLabel: 'Explore os serviços ↓', secondaryHref: '#solucoes', footnote: 'INFORMAÇÃO ANTES DA CONTRATAÇÃO.', scrollLabel: 'ROLE PARA CONHECER', scrollHref: '#solucoes', paperLabel: 'VAMOS CONVERSAR', paperTitle: 'Qual é o seu', paperHighlight: 'próximo passo?', paperFooter: 'Consultor de crédito consignado' },
  ticker: { visible: true, symbol: '✳', items: ['CONSIGNADO', 'PORTABILIDADE', 'REFINANCIAMENTO'] },
  solutions: { visible: true, eyebrow: '01 / SOLUÇÕES', title: 'Encontre o caminho\npara o seu crédito.', description: 'Selecione uma modalidade para entender como funciona e conversar sobre o seu caso.', footnote: 'Modalidades e condições dependem do seu perfil e da instituição financeira. Aprovação sujeita à análise.', items: [
    { icon: '↗', title: 'Empréstimo consignado', description: 'Entenda as parcelas descontadas em folha ou benefício e avalie uma opção que faça sentido para seu orçamento.', buttonLabel: 'Conhecer minhas opções', href: '#contato', featured: true },
    { icon: '⇄', title: 'Portabilidade de crédito', description: 'Compare seu contrato atual com outras condições e avalie a possibilidade de transferir seu crédito.', buttonLabel: 'Conhecer minhas opções', href: '#contato', featured: false },
    { icon: '⟳', title: 'Refinanciamento', description: 'Conheça as possibilidades de reorganizar seu contrato, considerando parcelas, prazo e custo total.', buttonLabel: 'Conhecer minhas opções', href: '#contato', featured: false }
  ] },
  profile: { fullName: 'Flaviano', role: 'Consultor de crédito consignado', company: 'Empresa de Crédito — exemplo', location: 'São Paulo / SP — exemplo', startYear: '2018', demo: true, demoNotice: 'Prévia demonstrativa · foto, experiência, empresa e certificações são placeholders.', experienceLabel: 'Atuação no crédito desde', companyLabel: 'Empresa', locationLabel: 'Região de atendimento', photoPlaceholder: 'Retrato profissional de Flaviano', trajectoryTitle: 'Minha trajetória profissional', credentialsTitle: 'Formação e certificações', milestones: [{ period: '2018 · exemplo', title: 'Início no mercado de crédito', description: 'Espaço para contar como começou sua atuação e quais experiências marcaram esse período.' }, { period: '2021 · exemplo', title: 'Atuação em crédito consignado', description: 'Descreva aqui sua experiência com clientes, modalidades e instituições.' }, { period: 'Hoje · exemplo', title: 'Atendimento e orientação', description: 'Conte como trabalha atualmente e o que considera importante em cada atendimento.' }], credentials: [{ title: 'Nome da certificação — exemplo', description: 'Instituição emissora · ano · registro. Substitua pelos dados reais e pelo link de verificação.', href: '#trajetoria' }], socialLinks: [{ label: 'LinkedIn — exemplo', href: '#contato' }, { label: 'Instagram — exemplo', href: '#contato' }] },
  about: { visible: true, eyebrow: '02 / QUEM ESTÁ COM VOCÊ', title: 'Sou Flaviano.\nVamos conversar?', paragraphs: ['Trabalho com crédito consignado e ajudo você a entender as possibilidades de contratação, portabilidade e refinanciamento.', 'No atendimento, a gente conversa sobre sua necessidade e analisa as condições: valor da parcela, prazo e custo total. Você tira suas dúvidas antes de decidir.'], photo: '/retrato-placeholder.svg', photoAlt: 'Imagem ilustrativa de perfil; substitua pela foto real de Flaviano', portraitLabel: 'PRAZER, FLAVIANO.', portraitText: 'Eu explico as opções.\nVocê toma a decisão.', signature: 'Flaviano', buttonLabel: 'Vamos nos conhecer ↗', href: '#contato', values: [{ title: 'Escuta de verdade', description: 'Sua necessidade é o ponto de partida.' }, { title: 'Clareza no processo', description: 'Espaço para perguntar e entender.' }] },
  process: { visible: true, eyebrow: '03 / PASSO A PASSO', title: 'Uma conversa.\nUm passo de cada vez.', description: 'Do primeiro contato à avaliação da proposta, você sabe qual é o próximo passo.', items: [{ title: 'A gente conversa', description: 'Você conta seu momento, suas dúvidas e o que está buscando.' }, { title: 'Você conhece as opções', description: 'Avaliamos as possibilidades e os detalhes das condições disponíveis.' }, { title: 'Você decide com clareza', description: 'Confira parcelas, prazo e custo efetivo total antes de seguir.' }] },
  faq: { visible: true, eyebrow: '04 / SUAS DÚVIDAS', title: 'O que você quer saber?', description: 'Informação clara faz parte do atendimento.', items: [{ question: 'Como funciona o crédito consignado?', answer: 'As parcelas são descontadas da folha de pagamento ou do benefício. A contratação depende da elegibilidade, da margem disponível e da análise da instituição financeira.' }, { question: 'O que devo comparar em uma proposta?', answer: 'Compare o Custo Efetivo Total (CET), as parcelas, o prazo e o total a pagar. Avalie o conjunto: uma parcela menor pode estar associada a um prazo maior.' }, { question: 'A portabilidade sempre vale a pena?', answer: 'Depende das condições do contrato atual e da nova proposta. É necessário comparar custos e prazo para avaliar o benefício.' }, { question: 'Este site armazena meus dados?', answer: 'O formulário prepara uma mensagem no seu dispositivo. Esta página não armazena os dados nem envia a mensagem automaticamente.' }] },
  contact: { visible: true, eyebrow: 'FALE COM FLAVIANO', title: 'Vamos entender\no seu momento.', description: 'Me diga seu nome e o assunto.\nVamos começar por aí.', signature: 'Flaviano ↗', whatsapp: '5500000000000', nameLabel: 'Como posso chamar você?', namePlaceholder: 'Seu primeiro nome', interestLabel: 'Sobre o que você quer conversar?', otherOption: 'Quero tirar uma dúvida', buttonLabel: 'Preparar minha mensagem ↗', footnote: 'Não informe documentos, senhas ou dados bancários.', messageTemplate: 'Olá, Flaviano! Meu nome é {nome}. Gostaria de conversar sobre {assunto}.', whatsappLabel: 'Abrir WhatsApp ↗', copyLabel: 'Copiar mensagem', copiedLabel: 'Mensagem copiada', copyError: 'Não foi possível copiar. Selecione a mensagem para copiar manualmente.', missingContact: 'O contato do consultor ainda precisa ser configurado.' },
  footer: { description: 'Flaviano / Crédito consignado', backToTop: 'Voltar ao topo ↑', copyright: '© 2026 Flaviano.', legalText: 'Conteúdo informativo. A contratação está sujeita às condições e à análise da instituição financeira. Avalie o custo total e o impacto das parcelas no seu orçamento.', links: [{label:'Perfil profissional — exemplo',href:'#sobre'}] },
  accessibility: { skipLabel: 'Pular para o conteúdo' }
};

export const groups = { brand: 'Marca', seo: 'Título e SEO', appearance: 'Aparência', header: 'Cabeçalho e menu', hero: 'Abertura e atendimento', ticker: 'Faixa de especialidades', solutions: 'Soluções', about: 'Sobre e foto', profile: 'Perfil e experiência', process: 'Etapas', faq: 'Perguntas frequentes', contact: 'Contato e WhatsApp', footer: 'Rodapé', accessibility: 'Acessibilidade' };
export const labels = { demo: 'Exibir aviso de conteúdo demonstrativo', demoNotice: 'Aviso dos placeholders', fullName: 'Nome completo', role: 'Cargo ou especialidade', company: 'Empresa', location: 'Cidade ou região atendida', startYear: 'Ano de início na área (AAAA)', experienceLabel: 'Legenda da experiência', companyLabel: 'Legenda da empresa', locationLabel: 'Legenda da região', photoPlaceholder: 'Texto provisório do retrato', trajectoryTitle: 'Título da trajetória', credentialsTitle: 'Título das certificações', milestones: 'Marcos da carreira', credentials: 'Formação e certificações', socialLinks: 'Perfis profissionais', period: 'Ano ou período', name: 'Nome', symbol: 'Símbolo', subtitle: 'Subtítulo da marca', title: 'Título', description: 'Descrição', orange: 'Cor principal', background: 'Fundo', text: 'Texto', animations: 'Ativar animações', menuLabel: 'Texto do menu móvel', contactLabel: 'Botão de contato', contactHref: 'Destino do contato', navigation: 'Links do menu', label: 'Texto do link', href: 'Destino do link', visible: 'Exibir seção', eyebrow: 'Texto acima do título', secondLine: 'Segunda linha do título', highlight: 'Texto em destaque', primaryLabel: 'Botão principal', primaryHref: 'Destino do botão principal', secondaryLabel: 'Botão secundário', secondaryHref: 'Destino do botão secundário', footnote: 'Observação', scrollLabel: 'Chamada para rolar', scrollHref: 'Destino ao rolar', paperLabel: 'Etiqueta do painel de atendimento', paperSymbol: 'Símbolo do papel', paperTitle: 'Título do painel de atendimento', paperHighlight: 'Destaque do painel de atendimento', paperFooter: 'Descrição do consultor', paperSteps: 'Linhas do papel', items: 'Itens', icon: 'Ícone ou símbolo', buttonLabel: 'Texto do botão', featured: 'Destacar item', paragraphs: 'Parágrafos', photo: 'Foto (URL ou imagem enviada)', photoAlt: 'Descrição acessível da foto', portraitLabel: 'Etiqueta da apresentação', portraitText: 'Texto da apresentação', signature: 'Assinatura', values: 'Diferenciais', question: 'Pergunta', answer: 'Resposta', whatsapp: 'WhatsApp (55 + DDD + número)', nameLabel: 'Rótulo do nome', namePlaceholder: 'Exemplo no campo nome', interestLabel: 'Rótulo do assunto', otherOption: 'Opção adicional', messageTemplate: 'Modelo de mensagem ({nome} e {assunto})', whatsappLabel: 'Botão do WhatsApp', copyLabel: 'Botão copiar', copiedLabel: 'Confirmação de cópia', copyError: 'Erro de cópia', missingContact: 'Aviso de contato ausente', backToTop: 'Voltar ao topo', copyright: 'Direitos autorais', legalText: 'Texto legal', links: 'Links adicionais', skipLabel: 'Pular ao conteúdo' };

// Only known fields are accepted. Imported content is rendered as text, never HTML.
export function normalizeConfig(input, template = defaults, path = '') {
  if (typeof template === 'string') {
    if (typeof input !== 'string' || input.length > (path.endsWith('.photo') ? 1500000 : 10000)) throw new Error(`Texto inválido em ${path}.`);
    if (/\.(orange|background|text)$/.test(path) && !/^#[0-9a-f]{6}$/i.test(input)) throw new Error(`Cor inválida em ${path}.`);
    if (/(Href|href)$/.test(path) && !/^(#|\/(?!\/)|https?:\/\/|mailto:|tel:)/i.test(input)) throw new Error(`Use um link válido em ${path}.`);
    if (path.endsWith('.photo') && input && !/^(https?:\/\/|\/(?!\/)|data:image\/(png|jpeg|webp);base64,)/i.test(input)) throw new Error('Use uma foto PNG, JPEG, WebP ou uma URL válida.');
    if (path.endsWith('.whatsapp') && input && !/^\d{12,13}$/.test(input)) throw new Error('WhatsApp deve conter 12 ou 13 dígitos, incluindo 55 e DDD.');
    if (path.endsWith('.startYear') && input && !/^(19|20)\d{2}$/.test(input)) throw new Error('Informe o ano com quatro dígitos.');
    return input;
  }
  if (typeof template === 'boolean') { if (typeof input !== 'boolean') throw new Error(`Opção inválida em ${path}.`); return input; }
  if (Array.isArray(template)) {
    if (!Array.isArray(input) || input.length > 30) throw new Error(`Lista inválida em ${path} (máximo 30 itens).`);
    const itemTemplate = template[0] ?? { label: '', href: '#' };
    return input.map((item, index) => normalizeConfig(item, itemTemplate, `${path}.${index}`));
  }
  if (!input || typeof input !== 'object' || Array.isArray(input)) throw new Error(`Configuração inválida em ${path}.`);
  return Object.fromEntries(Object.entries(template).map(([key, value]) => [key, normalizeConfig(input[key] ?? value, value, `${path}.${key}`)]));
}

// Upgrade only old default copy; preserve custom content and uploaded photos.
export function migrateConfig(input) {
 const config=normalizeConfig(input);
 for(const key of ['company','location','startYear']) if(!config.profile[key]) config.profile[key]=defaults.profile[key];
 for(const key of ['milestones','credentials','socialLinks']) if(!config.profile[key].length || config.profile[key].every(item=>!(item.title||item.label))) config.profile[key]=structuredClone(defaults.profile[key]);
 if(!config.about.photo) {config.about.photo=defaults.about.photo;config.about.photoAlt=defaults.about.photoAlt;}
 if(!config.contact.whatsapp) config.contact.whatsapp=defaults.contact.whatsapp;
 if(!config.footer.links.length) config.footer.links=structuredClone(defaults.footer.links);
 const previous={hero:{title:['Crédito.','Seu crédito,'],secondLine:['Sem','com orientação'],highlight:['rodeios.','de perto.'],description:['Consignado, portabilidade e refinanciamento.\nEu explico as opções. Você escolhe o próximo passo.'],paperLabel:['CRÉDITO CONSIGNADO','Crédito consignado'],paperTitle:['Vamos colocar\nas contas','Soluções para o seu'],paperHighlight:['no papel.','próximo passo.'],paperFooter:['ATENDIMENTO COM FLAVIANO','Atendimento pessoal com Flaviano']},solutions:{title:['O que você\nprecisa resolver?'],description:['Escolha um assunto. A gente começa pelo que importa para você.']},about:{title:['Pode me chamar\nde Flaviano.'],portraitText:['Crédito consignado.\nAtendimento pessoal.']},process:{title:['Como é o\natendimento.']},faq:{title:['Dúvidas comuns.\nRespostas diretas.']},contact:{title:['Vamos falar\ndo seu crédito?']},appearance:{orange:['#ef672b'],background:['#f6f3ed'],text:['#222321','#24272c']}};
 for(const [section,fields] of Object.entries(previous))for(const [key,values] of Object.entries(fields))if(values.includes(config[section][key]))config[section][key]=defaults[section][key];
 return config;
}
